#!/bin/bash

source "${BASH_SOURCE%/*}/functions"

leaveLog "CLEAR BROWSER HISTORY ${now}"

# Quit app first
osascript -e 'quit app "Google Chrome"'

# Backup Chrome history and cache
# 1. History
if [ ! -f "$chromeBackupLocation/History" ]; then
  run "cp -fr ~/Library/Application\ Support/Google/Chrome/Default/History ${chromeBackupLocation}"
  run "rm -rf ~/Library/Application\ Support/Google/Chrome/Default/History"
else
  leaveLog "$chromeBackupLocation/History file already exist"
fi
# 2. History-journal
if [ ! -f "$chromeBackupLocation/History-journal" ]; then
  run "cp -fr ~/Library/Application\ Support/Google/Chrome/Default/History-journal ${chromeBackupLocation}"
  run "rm -rf ~/Library/Application\ Support/Google/Chrome/Default/History-journal"
else
  leaveLog "$chromeBackupLocation/History-journal file already exist"
fi
# 3. Current Tabs
if [ ! -f "$chromeBackupLocation/Current Tabs" ]; then
  run "cp -fr ~/Library/Application\ Support/Google/Chrome/Default/Current\ Tabs ${chromeBackupLocation}"
  run "rm -rf ~/Library/Application\ Support/Google/Chrome/Default/Current\ Tabs"
else
  leaveLog "$chromeBackupLocation/Current\ Tabs file already exist"
fi
# 4. Cookies
if [ ! -f "$chromeBackupLocation/Cookies" ]; then
  run "cp -fr ~/Library/Application\ Support/Google/Chrome/Default/Cookies ${chromeBackupLocation}"
  run "rm -rf ~/Library/Application\ Support/Google/Chrome/Default/Cookies"
else
  leaveLog "$chromeBackupLocation/Cookies file already exist"
fi
# 5. Cookies-journal
if [ ! -f "$chromeBackupLocation/Cookies-journal" ]; then
  run "cp -fr ~/Library/Application\ Support/Google/Chrome/Default/Cookies-journal ${chromeBackupLocation}"
  run "rm -rf ~/Library/Application\ Support/Google/Chrome/Default/Cookies-journal"
else
  leaveLog "$chromeBackupLocation/Cookies-journal file already exist"
fi
# 6. Cache
if [ ! -d "$chromeBackupLocation/Cache" ]; then
  run "cp -fr ~/Library/Caches/Google/Chrome/Default/Cache ${chromeBackupLocation}"
  run "rm -rf ~/Library/Caches/Google/Chrome/Default/Cache"
else
  leaveLog "$chromeBackupLocation/Cache directory already exist"
fi
# 7. Media Cache
if [ ! -d "$chromeBackupLocation/Media Cache" ]; then
  run "cp -fr ~/Library/Caches/Google/Chrome/Default/Media\ Cache ${chromeBackupLocation}"
  run "rm -rf ~/Library/Caches/Google/Chrome/Default/Media\ Cache"
else
  leaveLog "$chromeBackupLocation/Media\ Cache directory already exist"
fi

# Quit app first
osascript -e 'quit app "Safari"'

# Backup Safari History (except for bookmarks).
# 1. History.db
if [ ! -f "$safariBackupLocation/History.db" ]; then
  run "cp -fr ~/Library/Safari/History.db ${safariBackupLocation}"
  run "rm -rf ~/Library/Safari/History.db"
else
  leaveLog "$safariBackupLocation/History.db file already exist"
fi
# 2. History.db-lock
if [ ! -f "$safariBackupLocation/History.db-lock" ]; then
  run "cp -fr ~/Library/Safari/History.db-lock ${safariBackupLocation}"
  run "rm -rf ~/Library/Safari/History.db-lock"
else
  leaveLog "$safariBackupLocation/History.db-lock file already exist"
fi
# 3. History.db-shm
if [ ! -f "$safariBackupLocation/History.db-shm" ]; then
  run "cp -fr ~/Library/Safari/History.db-shm ${safariBackupLocation}"
  run "rm -rf ~/Library/Safari/History.db-shm"
else
  leaveLog "$safariBackupLocation/History.db-shm file already exist"
fi
# 4. History.db-wal
if [ ! -f "$safariBackupLocation/History.db-wal" ]; then
  run "cp -fr ~/Library/Safari/History.db-wal ${safariBackupLocation}"
  run "rm -rf ~/Library/Safari/History.db-wal"
else
  leaveLog "$safariBackupLocation/History.db-wal file already exist"
fi
# 5. RecentlyClosedTabs.plist
if [ ! -f "$safariBackupLocation/RecentlyClosedTabs.plist" ]; then
  run "cp -fr ~/Library/Safari/RecentlyClosedTabs.plist ${safariBackupLocation}"
  run "rm -rf ~/Library/Safari/RecentlyClosedTabs.plist"
else
  leaveLog "$safariBackupLocation/RecentlyClosedTabs.plist file already exist"
fi
# 6. LastSession.plist
if [ ! -f "$safariBackupLocation/LastSession.plist" ]; then
  run "cp -fr ~/Library/Safari/LastSession.plist ${safariBackupLocation}"
  run "rm -rf ~/Library/Safari/LastSession.plist"
else
  leaveLog "$safariBackupLocation/LastSession.plist file already exist"
fi
# 7. LocalStorage
if [ ! -d "$safariBackupLocation/LocalStorage" ]; then
  run "cp -fr ~/Library/Safari/LocalStorage ${safariBackupLocation}"
  run "rm -rf ~/Library/Safari/LocalStorage"
else
  leaveLog "$safariBackupLocation/LocalStorage directory already exist"
fi

# Backup Cookies
# 1. Cookies
if [ ! -d "$backupLocation/Cookies" ]; then
  run "cp -fr ~/Library/Cookies ${backupLocation}"
  run "rm -rf ~/Library/Cookies"
else
  leaveLog "$backupLocation/Cookies directory already exist"
fi

leaveLog "=================="
notify "Backup Privacy"